const seedTeams=[
 {id:'seed-1',nickname:'哑猴',avatar:'🙊',gender:'保密',type:'2=1',need:['哑猴'],message:'通了三关了，找个靠谱的，玩得开心就行',time:1,online:true,steam:'456123789'},
 {id:'seed-2',nickname:'盲猴',avatar:'🙈',gender:'女生',type:'1=2',need:['聋猴','哑猴'],message:'声音好听的姐妹来~ 我声音一般但是会听hhh',time:2,online:true,steam:'880123456'},
 {id:'seed-3',nickname:'聋猴',avatar:'🙉',gender:'保密',type:'1=2',need:['盲猴','哑猴'],message:'我盲猴贼稳，不信你试试',time:4,online:true,steam:'147258369'},
 {id:'seed-4',nickname:'拆弹老司机',avatar:'🐵',gender:'男生',type:'2=1',need:['哑猴'],message:'我俩老玩家了，这次只找稳的',time:7,online:false,steam:'258369147'},
 {id:'seed-5',nickname:'奶茶三分糖',avatar:'🧋',gender:'女生',type:'1=2',need:['盲猴','聋猴'],message:'我比较菜...有大佬带带我吗 QAQ',time:8,online:true,steam:'880345678'},
 {id:'seed-6',nickname:'小钢炮',avatar:'💥',gender:'男生',type:'2=1',need:['盲猴'],message:'老玩家，喜欢快节奏，开局就拆弹',time:12,online:false,steam:'753159468'},
];
const state={filter:'all',search:'',editing:null,teams:JSON.parse(localStorage.getItem('bbn_replica_posts')||'[]')};
const $=s=>document.querySelector(s); const grid=$('#grid');
const deco={女生:'🎀',男生:'🧢',保密:'🕶️'}; const monkeys=['🙈','🙉','🙊','🐵'];
function allTeams(){return [...state.teams,...seedTeams].sort((a,b)=>a.createdAt?b.createdAt-a.createdAt:(a.time||0)-(b.time||0));}
function card(t){const [filled,need]=t.type.split('=').map(Number); const slots=Array.from({length:filled},(_,i)=>`<span class="slot ${t.gender==='女生'?'female':''}">${monkeys[(t.id.charCodeAt(0)+i)%4]}<i class="deco">${deco[t.gender]||'🕶️'}</i></span>`).join('')+Array.from({length:need},()=>'<span class="slot empty"></span>').join(''); const mine=state.teams.some(x=>x.id===t.id); return `<article class="card"><div class="card-top"><div class="type"><span class="num">${filled}</span> = <span class="num">${need}</span><span class="label">差 ${need} 人</span></div><span class="status ${t.online?'online':''}">${t.online?'<i></i>正在线':`${t.time} 分钟前在线`}</span></div><div class="slots">${slots}</div><div class="owner"><span class="owner-avatar">${t.avatar||'🐵'}</span><span class="owner-name">${t.nickname||'神秘猴'}</span><span class="owner-gender">${t.gender||'保密'}</span>${mine?'<span class="mine">我的</span>':''}</div><div class="need">${(t.need||[]).map(n=>`<span class="tag">${n}</span>`).join('')}</div><div class="message">${t.message||'等待一位默契队友加入'}</div><div class="card-foot"><span class="time">🕐 ${t.time<60?t.time+' 分钟前':'更早'}</span><button class="view" data-id="${t.id}">${mine?'✏️ 管理发布':'👥 查看队友'}</button></div></article>`;}
function render(){let ts=allTeams().filter(t=>state.filter==='all'||t.type===state.filter);if(state.search){const q=state.search.toLowerCase();ts=ts.filter(t=>[t.nickname,t.steam,t.message].some(v=>(v||'').toLowerCase().includes(q)));}grid.innerHTML=ts.map(card).join('');$('#count').textContent=`· ${ts.length} 队`;$('#empty').hidden=ts.length>0;grid.querySelectorAll('.view').forEach(b=>b.onclick=()=>{const t=allTeams().find(x=>x.id===b.dataset.id);if(!t)return;if(state.teams.some(x=>x.id===t.id)) openModal(t); else openDetail(t);});}
function openModal(t=null){state.editing=t?.id||null;$('#modalTitle').textContent=t?'管理发布':'发布组队';$('#nickname').value=t?.nickname||'';$('#steam').value=t?.steam||'';$('#message').value=t?.message||'';$('#need').value=(t?.need||[]).join('、');$('#onlineTime').value=t?.onlineTime||'';document.querySelector(`input[name=teamType][value="${t?.type||'1=2'}"]`).checked=true;document.querySelector(`input[name=gender][value="${t?.gender||'女生'}"]`).checked=true;let d=$('#deleteCurrent');if(!d){d=document.createElement('button');d.id='deleteCurrent';d.type='button';d.textContent='下架这条发布';d.style.cssText='margin-right:auto;border:1px solid #ff6f6f;border-radius:10px;padding:10px 14px;background:rgba(255,90,90,.1);color:#ff8d8d;font-weight:700;cursor:pointer';document.querySelector('.form-actions').prepend(d);}d.hidden=!t;d.onclick=()=>{state.teams=state.teams.filter(x=>x.id!==state.editing);localStorage.setItem('bbn_replica_posts',JSON.stringify(state.teams));closeModal();render();toast('已下架这条发布');};$('#modal').hidden=false;}
function openDetail(t){$('#detailTitle').textContent=`${t.avatar||'🐵'} ${t.nickname}`;$('#detailBody').innerHTML=`<div class="detail-list"><div class="detail-row"><span>性别</span><b>${t.gender||'保密'}</b></div><div class="detail-row"><span>正在寻找</span><b>${(t.need||[]).join('、')||'默契队友'}</b></div><div class="detail-row"><span>留言</span><b>${t.message||'暂无留言'}</b></div><div class="detail-row"><span>在线时段</span><b>${t.onlineTime||'随时在线'}</b></div></div><button class="primary copy-wide" id="copyDetail">复制 Steam 码 · ${t.steam}</button>`;$('#detailModal').hidden=false;$('#copyDetail').onclick=()=>{navigator.clipboard?.writeText(t.steam);toast('Steam 码已复制');};}
function closeModal(){$('#modal').hidden=true;state.editing=null;} function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800);}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;render();});$('#search').oninput=e=>{state.search=e.target.value;render();};['#heroPost','#floatPost'].forEach(s=>$(s).onclick=()=>openModal());['#closeModal','#cancelModal'].forEach(s=>$(s).onclick=closeModal);$('#closeDetail').onclick=()=>$('#detailModal').hidden=true;$('#postForm').onsubmit=e=>{e.preventDefault();const t={id:state.editing||'user-'+Date.now(),nickname:$('#nickname').value||'神秘猴',steam:$('#steam').value,type:document.querySelector('input[name=teamType]:checked').value,gender:document.querySelector('input[name=gender]:checked').value,need:$('#need').value.split(/[、,，]/).map(x=>x.trim()).filter(Boolean),message:$('#message').value,onlineTime:$('#onlineTime').value,time:0,online:true,createdAt:Date.now()};state.teams=state.editing?state.teams.map(x=>x.id===state.editing?t:x):[t,...state.teams];localStorage.setItem('bbn_replica_posts',JSON.stringify(state.teams));closeModal();render();toast(state.editing?'已更新你的组队':'已发布到大厅');};render();
